version: '2'

services:
  waterchatpostgres:
     image: waterchatpostgres
     restart: always
     build:
       context: .
       dockerfile: Dockerfile
     ports:
       - 5432:5432
     environment:
         POSTGRES_PASSWORD: waterchat
     volumes:
       - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: