variables:
  PROJECT_GROUP: waterchat
  PROJECT_NAME: gateway

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -f Dockerfile.gateway -t $PROJECT_GROUP/$PROJECT_NAME .
  tags:
    - shell

deploy:
  stage: deploy
  script:
    - docker stack rm $PROJECT_GROUP
    - docker stack deploy -c docker-compose.yml $PROJECT_GROUP
  tags:
    - shell
