variables:
  PROJECT_GROUP: waterchat
  PROJECT_NAME: gateway

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - docker stack deploy -c docker-compose.yml $PROJECT_GROUP
    - | 
        docker stack services -q waterchat | while read service; do
          docker service update --force $service
        done
  tags:
    - shell
