variables:
  PROJECT_GROUP: waterchat
  PROJECT_NAME: gateway

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - docker stack deploy -c docker-compose.yml $PROJECT_GROUP
  tags:
    - shell
