variables:
  PROJECT_GROUP: waterchat
  PROJECT_NAME: gateway
  AUTH_SERVICE: ${PROJECT_GROUP}_micro-auth
  MESSAGE_SERVICE: ${PROJECT_GROUP}_messages

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - docker stack deploy -c docker-compose.yml $PROJECT_GROUP
    - docker service update --force $AUTH_SERVICE
    - docker service update --force $MESSAGE_SERVICE
  tags:
    - shell
