version: '3'

services:
  kong-database:
    image: cassandra:3
    volumes:
      - /home/cap3/kong/cassandra:/var/lib/cassandra
    ports:
      - "9042:9042"
  kong:
    image: kong:0.10
    depends_on:
      - kong-database
    environment:
      - KONG_DATABASE=cassandra
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_PG_HOST=kong-database
    ports:
      - "80:8000"
      - "443:8443"
      - "8001:8001"
      - "7946:7946"
      - "7946:7946/udp"
  kong-dashboard:
    image: pgbi/kong-dashboard:v2
    ports:
      - "8080:8080"
    depends_on:
      - kong
  eventstore:
    image: eventstore/eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
    volumes:
      - /home/cap3/eventstore/data:/var/lib/eventstore
  micro-auth:
    image: waterchat/micro-auth:latest
    ports:
      - "3030:3000"
    depends_on:
      - eventstore
