version: '3'

services:
  kong-database:
    image: postgres:9.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    volumes:
      - "/home/cap3/kong/postgres:/var/lib/postgresql/data"
    networks:
      - waterchat
  kong:
    image: kong:0.10
    depends_on:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    ports:
      - "80:8000"
      - "443:8443"
      - "8001:8001"
      - "7946:7946"
      - "7946:7946/udp"
    networks:
      - waterchat
  kong-dashboard:
    image: pgbi/kong-dashboard:v2
    ports:
      - "8080:8080"
    depends_on:
      - kong
    networks:
      - waterchat
  eventstore:
    image: eventstore/eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
    volumes:
      - /home/cap3/eventstore/data:/var/lib/eventstore
    networks:
      - waterchat
  micro-auth:
    image: waterchat/micro-auth:latest
    ports:
      - "3030:3000"
    depends_on:
      - eventstore
    networks:
      - waterchat
  messages:
    image: waterchat/messages:latest
    ports:
      - "4000:4000"
    depends_on:
      - eventstore
    networks:
      - waterchat
networks:
  waterchat:
  