version: '3'

services:
  kong-database:
    image: cassandra:3
    volumes:
      - /home/cap3/kong/cassandra:/var/lib/cassandra
    ports:
      - "9042:9042"
    networks:
      - waterchat
  kong:
    image: kong:0.10
    environment:
      - KONG_DATABASE=cassandra
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_PG_HOST=kong-database
    ports:
      - "80:8000"
      - "443:8443"
      - "8001:8001"
      - "7946:7946"
      - "7946:7946/udp"
    networks:
      - waterchat
  kong-dashboard:
    image: pgbi/kong-dashboard:v2
    ports:
      - "8080:8080"
    networks:
      - waterchat
  eventstore:
    image: eventstore/eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
    volumes:
      - /home/cap3/eventstore/data:/var/lib/eventstore
    networks:
      - waterchat
  micro-auth:
    image: waterchat/micro-auth
    ports:
      - "3030:3000"
    environment:
      - GITHUB_CALLBACK
      - GITHUB_ID
      - GITHUB_SECRET
    depends_on:
      - eventstore
    networks:
      - waterchat

networks:
    waterchat:

