FROM ubuntu:14.04
MAINTAINER Muninn <hyacinthus@gmail.com>

LABEL caddy_version="0.10.3" architecture="amd64"

RUN apt-get update
RUN apt-get install -y curl

RUN curl https://getcaddy.com | bash

EXPOSE 80 443 2015
VOLUME /root/.caddy
WORKDIR /www

COPY Caddyfile /etc/Caddyfile

ENTRYPOINT ["/usr/local/bin/caddy"]
CMD ["--conf", "/etc/Caddyfile", "--log", "stdout"]